name: Auto Deploy to Windows

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH vào Windows và cập nhật web
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.1.102                 # IP máy bạn
          username: vu van duong               # tên user Windows 
          password: ${{ secrets.WIN_PASS }}    # mật khẩu Windows bạn sẽ tạo secret
          port: 22
          script: |
            cd "D:\Class1"                     # thư mục dự án của bạn
            git pull
            docker-compose down                # dừng container cũ
            docker-compose up -d --build       # build lại + chạy ngầm
            echo "Deploy thành công lúc $(date)"